apiVersion: temporal.io/v1alpha1
kind: WorkerDeployment
metadata:
  name: valet-worker
  namespace: default
spec:
  workerOptions:
    connectionRef:
      name: cluster-default
    temporalNamespace: default
  rollout:
    strategy: Manual
  sunset:
    scaledownDelay: 30s
    deleteDelay: 2m
  replicas: 1
  template:
    spec:
      containers:
        - name: valet-worker
          image: valet-worker:4.0
          imagePullPolicy: IfNotPresent
