apiVersion: temporal.io/v1alpha1
kind: TemporalWorkerDeployment
metadata:
  name: valet-worker
  namespace: default
spec:
  workerOptions:
    connectionRef:
      name: cluster-default
    temporalNamespace: default
  rollout:
    strategy: AllAtOnce
  # TODO (Part B): Switch to the Progressive rollout strategy
  # rollout:
  #   strategy: Progressive
  #   steps:
  #     - rampPercentage: 25
  #       pauseDuration: 30s
  #     - rampPercentage: 75
  #       pauseDuration: 30s
  # TODO (Part C): Switch to the Manual rollout strategy
  # rollout:
  #   strategy: Manual
  # TODO (Part D): Switch to Progressive with a gate
  # rollout:
  #   strategy: Progressive
  #   steps:
  #     - rampPercentage: 25
  #       pauseDuration: 30s
  #     - rampPercentage: 75
  #       pauseDuration: 30s
  #   gate:
  #     workflowType: "ValetGateWorkflow"
  sunset: {}
  replicas: 1
  template:
    spec:
      containers:
        - name: valet-worker
          image: valet-worker:1.0
          # TODO (Part B): Switch to the 2.0 image
          # image: valet-worker:2.0
          imagePullPolicy: IfNotPresent
